@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/1

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "title": "I must create an App",
    "description": "using react native"
}

###
DELETE {{api}}/23

###
PUT {{api}}/3
Content-Type: application/json

{
    "description": "descripcion tres!!!",
    "title": "titulo 3"
}
